### ISSUE TITLE
Bluetack lists are not free

### ISSUE THREAD

**Issue by ghost** [ktsaou/blocklist-ipsets#1]
>
[iBlocklist.com](https://www.iblocklist.com/) free version of BlueTack.co.uk IPs

Actually the lists you included from bluetack are redistributed by iblocklist without permission. There are no free versions. 

Great work on everything else though.

**Comment by ktsaou** [comment]
Hi Mike,

I am very sorry. I didn't know. I believed they are limited or delayed feeds of your commercial versions which you want to be distributed freely.

This is what I just did:

- I removed bluetack lists from the gihub repo, so I stopped their redistribution via my sites.
- I removed the word `free` from the comments.

Questions:

1. Do you want me to remove completely anything related to them?

2. May I get your commercial lists just for comparing them with the other blocklists? I will not redistribute your content. I will just download it and update the comparison site. I can also add some info or ad for you (free of charge of course). If you allow me to do this, FireHOL's `update-ipsets.sh` script will be ready for your customers that happen to be my users too, to use your lists out of the box.

Regards

**Comment by Mike-XSI** [comment]
HI Costa,

Thanks for the reply. I really appreciate your efforts to clear up any confusion. I wish there were more people like you in the world. 

I understand that iblocklist don't give any details about their operations, so you have no way of knowing what they are doing to other people / sites.

1: Bluetack will be closing down soon. After that I'm not sure those lists will still be available anymore. At least not from Bluetack. Last I looked, the blocklist documentation iblocklist stole from Bluetack was also innacurate and outdated. 

We have had a lot of changes and new lists. My main blocklist is now the Hostile Servers list for server firewalls. We also have a new Intrusion Detection list that I've been building from server attacks and honeypots. Single IP's go into the IDS list and the CIDR range goes into Hostile Servers.

2 : I would love to help anyway that I can. I'm really impressed with your work.
While Bluetack is still online I can give you a free subscription to check out the lists. 

If you don't mind, I can send you an email with more details.

**Comment by ktsaou** [comment]
Thanks Mike,

Yes, please send me whatever private info you believe will help at costa@tsaousis.gr. If if the information is public, github issues is preferred.

I am very sorry you are going to close Bluetack.

I decided to build the blocklist-ipsets site and repo because I think the infosec community is very cryptic. It is a shame! So many teams, so many ideas, so much software, hidden, cryptic, incomplete, inefficient...

What I am trying to achieve is somehow combine the efforts of anyone willing to help. I don't know the solution yet. Time will show the roadmap I guess.

Regards,

Costa

**Comment by Mike-XSI** [comment]
Dear Costa, since you are unwilling to remove any of the information you have stolen from the bluetack site, can you at least not put bluetack and iblocklist in the same sentence.

There is no such thing as a iblocklist version of a bluetack list. The lists at iblocklist are stolen from bluetack and now distributed without permission by you and many others. 

In case you still don't get it. Let me put it in another perspective.

Imagine Fakhir took Firehol and put it on iblocklist and started selling it to people, without asking you or giving a shit if you asked him not to do that. 

You and Fakhir are totally disrespecting Tozzano's memory and it's disgusting.

**Comment by ktsaou** [comment]
I received by email the following comment, which was apparently deleted from github:

> Dear Costa, since you are unwilling to remove any of the information you have stolen from the bluetack site, can you at least not put bluetack and iblocklist in the same sentence.

> There is no such thing as a iblocklist version of a bluetack list. The lists at iblocklist are stolen from bluetack and now distributed without permission by you and many others.

> In case you still don't get it. Let me put it in another perspective.

> Imagine Fakhir took Firehol and put it on iblocklist and started selling it to people, without asking you or giving a shit if you asked him not to do that.

> You and Fakhir are totally disrespecting Tozzano's memory and it's disgusting.

Dear Mike, I am very sorry for the inconvenience.

This is my view:

1. My site is reviewing IP lists. I do this to help the infosec community understand the IP lists it uses, provide updated directions for the IP lists available, their sources, their maintainers, etc.

2. I don't steal content. By default, I re-distribute IP lists that are already publicly available, when their license does not forbid re-distribution. I do this to help users get the IP lists in a standard format. I always contact the maintainers of the IP lists for their presence on this site. I have already contacted iblocklist.com, the time I added their IP lists to the site. Also I always disable re-distribution if a maintainer notifies me that they do not want this re-distribution to happen.

 Keep in mind, that I stopped re-distributing iblocklist.com lists that, according to iblocklist.com are authored by bluetack.co.uk, based on YOUR complaint. I have not verified who you are. But since someone feels uncomfortable with it, I stopped it immediately.

3. Given the above, I don't understand your claim that "I have stolen information from bluetack site". Could you please pin point that information for me? Where in my site there is content stolen from bluetack? I don't steal anything.

4. You say "there is no such thing as an iblocklist version of a bluetack list".
 How do you interpret the following screenshot?

![image](https://cloud.githubusercontent.com/assets/2662304/9955722/fa48ed5c-5dfb-11e5-9359-a8c9f88687cf.png)

iblocklist.com provides a publicly available IP list they say it comes from bluetack.co.uk. How should I describe this IP list?

Anyway, I will try to rename the ib_bluetack_* lists in the weekend to remove 'bluetack' from their names and descriptions.

However, I don't understand why I am accused of stealing. This is very frustrating for me, given that my intentions are to help without breaking any license or the interests of anyone.

Kind Regards,

Costa

**Comment by ktsaou** [comment]
I renamed all iblocklist lists. Bluetack does not appear anywhere now.
If you agree with this settlement, please close this issue.
Otherwise, please let know which issue remains.

**Comment by ktsaou** [comment]
It seems that the user that opened this issue is deleted from github.
I consider this issue closed.
